name: Upload to host

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initiate Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0
      - name: Generate Web version
        run: |
          npm i && npm run build
          rm -rf dbwp/wp-content/themes/dbands_OO/assets_dev

      - name: Rclone
        run: |
          apt-get update -qqy && apt-get upgrade -qqy
          apt-get install -qqy curl unzip
          curl https://rclone.org/install.sh | bash
          rclone config create remote sftp host=${{ secrets.FTP_HOST }} user=${{ vars.SERVER_USER }} key_file=${{ secrets.SSH_PRIVATE_KEY }}
          rclone copyto dbwp/ remote:${PATH_DIR}/

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: ${{vars.SMTP_HOST}}
          from-email: ${{vars.SMTP_USER}}
          to-email: fagnerjb@gmail.com
          username: ${{vars.SMTP_USER}}
          password: ${{secrets.SMTP_PASS}}
          subject: Deploy done
          html: |
            <p>Deploy done of ${{github.ref_name}} in ${{github.repository}}</p>
            <p><a href="https://dbands.com.br/">dbands.com.br</a></p>
